version: 2
updates:
  # docs v2 https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
  - package-ecosystem: "npm"
    # DISABLE dependabot on this repo: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#disabling-dependabot-version-updates
    open-pull-requests-limit: 0
    schedule:
      interval: "monthly"
      # Check for npm updates on Sundays
      day: "saturday"
    allow:
      - dependency-type: "production"
    directory: "/"
    commit-message:
      # for production deps, prefix commit messages with "fix" (trigger a patch release)
      prefix: "fix"
      # for development deps, prefix commit messages with "chore" (do NOT trigger an npm release)
      prefix-development: "chore"
      include: "scope"
