process.env.DEBUG = ""
process.env.WAS_CSRF_SECRET = "jest-secret"
process.env.SESSION_TOKEN_SECRET = "jest-secret"
process.env.CSRF_TOKEN_WARNING_DISABLE = ""
process.env.TOKENATER_WARNING_DISABLE = ""
process.env.WAS_SESSION_SECRET = "test-secret"